### ISSUE TITLE
能否将矩形标注产生的锚文本去除

### ISSUE THREAD

**Issue by Chenm4** [zxhd863943427/siyuan-plugin-pdf-annotate-enhance#1]
![image](https://github.com/zxhd863943427/siyuan-plugin-pdf-annotate-enhance/assets/98648589/7dbca14f-c92b-4c41-8fd8-9b92891b615c)
因为矩形标注每次产生PDF名字的锚文本，如果使用次数较多感觉整个文档出现书名的锚文本很频繁不是很美观，但是又很需要跳转到对应位置这个功能，能否实现字图片右上角某个位置添加一个按钮点击就能跳转的功能？这样就可以去掉锚文本了

**Comment by zxhd863943427** [comment]
你好，这个需要siyuan增加插件接口，目前没有办法简单地自定义图片按钮。
